kind: pipeline
type: docker
name: build

clone:
  disable: true

steps:
  - name: build-image # 步骤名称
    image: plugins/docker # 使用镜像
    settings: # 当前设置
      username: # 账号名称
        from_secret: docker_username
      password: # 账号密码
        from_secret: docker_password
      dockerfile: Dockerfile # Dockerfile地址， 注意是相对地址
      repo: yangmei1219/ankr # 镜像名称
      tags:
        - ${DRONE_COMMIT}
        - latest

trigger:
  branch:
    - main
  event:
    - push