kind: pipeline
type: docker
name: ankr

clone:
  disable: false

steps:
  # 使用缓存
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: node_cache
        path: /cache

  - name: ssh-deploy
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.104
      username: yangmei
      password:
        from_secret: server-password
      repo_username:
        from_secret: docker_username
      repo_password:
        from_secret: docker-password
      port: 22
      script:
        - docker login --username=${repo_username} --password=${repo_password} yangmei1219
        - docker pull yangmei1219/ankr:latest
        - docker stop ankr || true && docker rm ankr || true
        - docker run -d --publish=8088:8088 -name=ankr --restart=always yangmei1219/ankr:latest

trigger:
  branch:
    - main
  event:
    - push